In [1]:
# calc_multi関数を定義
def calc_multi(a,b):
    return a * b

calc_multi(3,10)

30

In [2]:
(lambda a,b:a * b)(3,10)

30

In [3]:
sample_str = "Data Science"

In [6]:
for i in range(0,len(sample_str)):
    print(sample_str[i])

D
a
t
a
 
S
c
i
e
n
c
e


In [7]:
print(sum(range(0,51)))

1275


In [8]:
class PrintClass:
    def print_me(self):
        print(self.x,self.y)
        
p1 = PrintClass()

p1.x = 10
p1.y = 100
p1.z = 1000

p1.print_me()

10 100


In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [2]:
data = np.array([9,2,3,4,10,6,7,8,1,5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [3]:
data.dtype

dtype('int32')

In [4]:
print('次元数',data.ndim)
print('要素数',data.size)

次元数 1
要素数 10


In [5]:
data1 = data * 2
print(data1)

[18  4  6  8 20 12 14 16  2 10]


In [6]:
print(data)
data.sort()

print(data)

[ 9  2  3  4 10  6  7  8  1  5]
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print('Min:',data.min())
print('Max:',data.max())

Min: 1
Max: 10


In [9]:
print('Sum:',data.sum())
print('Cum:',data.cumsum())
print('Ratio:',data.cumsum()/data.sum())

Sum: 55
Cum: [ 1  3  6 10 15 21 28 36 45 55]
Ratio: [0.018 0.055 0.109 0.182 0.273 0.382 0.509 0.655 0.818 1.   ]


In [10]:
random.seed(0)

# 正規分布（平均０、分散１）の乱数を１０個生成
rnd_data = random.randn(10)

print('乱数10個の配列:',rnd_data)

乱数10個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [11]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

# ランダム抽出
# 10個を抽出
print(random.choice(data,10))

# 10個を抽出（重複無し、非復元抽出）
print(random.choice(data,10,replace=False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


In [12]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
array1[0]

array([0, 1, 2])

In [15]:
array1[0][1]

1

In [16]:
array1[1][1]

4

In [17]:
data = np.arange(51)
tmp = data.sum()

In [18]:
print(tmp)

1275


In [19]:
rnd_data = random.randn(10)
print(rnd_data)

[ 1.494 -0.205  0.313 -0.854 -2.553  0.654  0.864 -0.742  2.27  -1.454]


In [20]:
min_rnd_data = rnd_data.min()

In [21]:
print(min_rnd_data)

-2.5529898158340787


In [22]:
max_rnd_data = rnd_data.max()
print(max_rnd_data)

2.2697546239876076


In [23]:
tmp = rnd_data.sum()
print(tmp)

-0.21381832081082974


In [24]:
a = np.ones((5,5)) * 3
print(a)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [25]:
print(a ** 2)

[[9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]]


In [26]:
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

In [28]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

print('行列式')
print(linalg.det(matrix))

行列式
-4.0
