In [1]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

In [2]:
sample_array = np.arange(10)
print('sample_array:',sample_array)

sample_array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
print(sample_array)

sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [4]:
sample_array_slice[0:3] = 10
print(sample_array_slice)

print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [5]:
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)
print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [6]:
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [7]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [8]:
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [11]:
cond_data = np.array([True,True,False,False,True])
x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])

print(np.where(cond_data,x_array,y_array))

[  1   2 300 400   5]


In [12]:
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [13]:
data[sample_names ==  'b']

array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [14]:
data[sample_names != 'c']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [16]:
cond_data = np.array([False,False,True,True,False])
x_array = np.array([1,2,3,4,5])
y_array = np.array([6,7,8,9,10])

In [17]:
print(np.where(cond_data,x_array,y_array))

[ 6  7  3  4 10]


In [18]:
cond_data = np.array([True,True,False,False,True])
print(cond_data)

print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [19]:
sample_data = np.arange(10)
print('元のデータ：',sample_data)
print('全ての要素の平方根：',np.sqrt(sample_data))
print('すべての要素のネイピア指数関数：',np.exp(sample_data))

元のデータ： [0 1 2 3 4 5 6 7 8 9]
全ての要素の平方根： [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイピア指数関数： [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [20]:
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
print('sample_multi_array_data2のすべての要素の平方根：',np.sqrt(sample_multi_array_data2))

sample_multi_array_data2のすべての要素の平方根： [[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [22]:
print(sample_multi_array_data2.min())

0


In [23]:
print(sample_multi_array_data2.max())

15


In [24]:
print(sample_multi_array_data2.mean())

7.5


In [25]:
print(np.diag(sample_multi_array_data2))
print(np.trace(sample_multi_array_data2))

[ 0  5 10 15]
30


In [26]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
sample_array2 = sample_array.reshape(2,5)
print(sample_array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
print(sample_array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [30]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

np.concatenate([sample_array3,sample_array4],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
np.vstack((sample_array3,sample_array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
np.concatenate([sample_array3,sample_array4],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [33]:
np.hstack((sample_array3,sample_array4))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [34]:
sample_array_vstack = np.vstack((sample_array3,sample_array4))
sample_array_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
first,second,third = np.split(sample_array_vstack,[1,3])
print(first)
print(second)
print(third)

[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[10 11 12]]


In [38]:
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)

sample_array3 = np.concatenate([sample_array1,sample_array2],axis=1)
print(sample_array3)

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [39]:
sample_array4 = np.concatenate([sample_array1,sample_array2],axis=0)
print(sample_array4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
sample_list = [1,2,3,4,5]
sample_list = np.array(sample_list)

In [44]:
print(sample_list,type(sample_list))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [45]:
sample_list + 3

array([4, 5, 6, 7, 8])